CC := ./
TARGET = Nand Not And Or Xor Mux DMux And16 Not16 Or16 Mux16 Or8Way DMux4Way DMux8Way Mux4Way16 Mux8Way16

all: $(TARGET)

Nand: Nand.out
	$(CC)$^

Not: Not.out
	$(CC)$^

And: And.out
	$(CC)$^

Or: Or.out
	$(CC)$^

Xor: Xor.out
	$(CC)$^

Mux: Mux.out
	$(CC)$^

DMux: DMux.out
	$(CC)$^

And16: And16.out
	$(CC)$^

Not16: Not16.out
	$(CC)$^

Or16: Or16.out
	$(CC)$^	

Mux16: Mux16.out
	$(CC)$^

Or8Way: Or8Way.out
	$(CC)$^

DMux4Way: DMux4Way.out
	$(CC)$^

DMux8Way: DMux8Way.out
	$(CC)$^

Mux4Way16: Mux4Way16.out
	$(CC)$^

Mux8Way16: Mux8Way16.out
	$(CC)$^
