CC := ./
TARGET = DFF Bit Register RAM8 RAM64 PC RAM512 RAM8K

all: $(TARGET)

DFF: DFF.out
	$(CC)$^

Bit: Bit.out
	$(CC)$^

Register: Register.out
	$(CC)$^

RAM8: RAM8.out
	$(CC)$^

RAM64: RAM64.out
	$(CC)$^

PC: PC.out
	$(CC)$^

RAM512: RAM512.out
	$(CC)$^

RAM8K: RAM8K.out
	$(CC)$^
