CC := ./
TARGET = Add16 ALU FullAdder HalfAdder Inc16

all: $(TARGET)

Add16: Add16.out
	$(CC)$^

ALU: ALU.out
	$(CC)$^

FullAdder: FullAdder.out
	$(CC)$^

HalfAdder: HalfAdder.out
	$(CC)$^

Inc16: Inc16.out
	$(CC)$^